### ISSUE TITLE
simple_hash_from_byte_slices should take a Vec instead of slice

### ISSUE THREAD

**Issue by ebuchman** [interchainio/tendermint-rs#57]
Currently we have `fn simple_hash_from_byte_slices(byte_slices: &[&[u8]]) -> Hash`

But this leads to some complexities in the few places it's so far used: 
- https://github.com/interchainio/tendermint-rs/blob/10a3026cfbd4ab333752d344645a4f07ecdc29f7/tendermint/src/validator.rs#L23-L35
- https://github.com/interchainio/tendermint-rs/pull/36/files#diff-a1644bb72a1c83c54d82738ef71ce095R126 (ie. the need for a separate variable followed by `as_slice` would go away)

**Comment by Liamsi** [comment]
Although it looks like a good idea, we should also consider that in Rust it is "more common to pass slices as arguments rather than vectors when you just want to provide a read access"
(ref: https://doc.rust-lang.org/std/vec/struct.Vec.html#slicing)

There is even a clippy warning about `fn(&Vec)` which we'd need to disable then: https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg 
ref #59

**Comment by ebuchman** [comment]
Oh hmm. I was thinking we'd want `Vec<Vec<u8>>`. It seems justified since if I'm not mistaken these arguments are not used again and so can be moved and consumed by this function.

That said for the recursion we may want an inner function that deals in slices so we don't need to_vec everywhere!

**Comment by tarcieri** [comment]
@ebuchman you can always add a From impl that consumes (or creates) a `Vec`
